### ISSUE TITLE
password reset can damage account

### ISSUE THREAD

**Issue by ghost** [hzi-braunschweig/pia-system#2]
If a hacker knows the username of a person, he can ask for a password reset. The user is forced to create a new password then, because the old one does not work any longer.

Suggestion: the old password should be valid until the user has changed the password on the next login.

Reproduce:

* click the "forgot password" link on the login page with a filled in username field
* you cannot login again with your known password, instead, you have to check your mail for the new password

**Comment by ghdoergeloh** [comment]
Dear @joerghenkebuero,
our capacity is very limited right now and we have some other tasks in planning. Therefore, we are sorry that the answers are so delayed. However, we will include these issues in our sprints.

Thank you for this hint. We are currently planning to refactor the authentication-part of PIA by using [Keycloak](https://www.keycloak.org/) (which has the highest priority, but it is a huge task so it could take some time) and this should then also fix this issue.

For now a username is not public and it is also not send to the user by email so for now "If a hacker knows the username" is the barrier a hacker has to overcome. But we know that this is not yet a complete solution.

**Comment by RobYed** [comment]
Dear @joerghenkebuero,
We are closing this issue, as PIA Version 1.30.0 and higher uses a completely reworked authentication mechanism which follows current standards. Thanks again for reporting this.
