### ISSUE TITLE
Export functionality: value not found in valuelist

### ISSUE THREAD

**Issue by ghost** [hzi-braunschweig/pia-system#9]
We have considered a bug that might be repaired on data input, but not in the value lists:
if a value list contains elements that end with a space, the space will not be recorded in the selected answer. Therefore, looking up that answer in the list of values will fail.

Example:
value list = "Antwort 1 ", "Antwort 2"
value = "Antwort 1"

`value` is not part of `value list`, because value does not have the trailing space character.

To reproduce: create a value list with spaces at the end, record data and export that data in the role of a PIA Probandenmanagement user.

**Comment by irinajanzen-hzi** [comment]
Thanks for the feedback. Some questions for clarification:
-  Are we talking about the questionnaire export as a researcher?
-  What answer type does the question where the bug appears have? Single Choice, Mulitple Choice, ...

**Comment by ghost** [comment]
Yes, this was found after exporting the questionnaire answers as a researcher. However, we have analyzed the export again and did not find that bug any longer. Maybe, this has been through splitting up the multiple choice values with an automatic trim functionality that we were not aware of.

Sorry for the inconvenience.
